### ISSUE TITLE
1.7 Support

### ISSUE THREAD

**Issue by CrazyWords1** [btk5h/skript-mirror#101]
**Describe the bug**
Addon loading with error on 1.7.10

**To reproduce**
Use a example skript, from skunity

**Expected behavior**
On Skunity written that there is support 1.7

**Screenshots**
`[22:10:29] [Server thread/INFO]: [skript-mirror] Enabling skript-mirror v0.19.1
[22:10:29] [Server thread/ERROR]: Error occurred while enabling skript-mirror v0.19.1 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/lang/function/Function
	at com.btk5h.skriptmirror.util.SkriptReflection.<clinit>(SkriptReflection.java:55) ~[?:?]
	at com.btk5h.skriptmirror.SkriptMirror.onEnable(SkriptMirror.java:24) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Server information**
- skript-mirror: skript-mirror 0.19.1
- Skript: 2.1.2
- Bukkit: Thermos
- Minecraft: 1.7.10
- Java: java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
- OS: Debian 8

**Additional context**

**Comment by btk5h** [comment]
skript-mirror is not dependent on Minecraft version, but it does require Skript 2.2 or later.
