### ISSUE TITLE
log handler error spam and freeze

### ISSUE THREAD

**Issue by melinstagibson** [btk5h/skript-mirror#110]
I  get this when i start my server after the latest paperspigot update

```
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:580)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 2 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1602)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 8 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1602)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.Statement.parse(Statement.java:54)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 7 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 5 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1602)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 8 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 9 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 2 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.Statement.parse(Statement.java:54)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 2 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:55:10 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
```
and many more, the server also freezes most of the time but not always
The problem is fixed when i remove skript-mirror so i guess here might be a good start?
paperspigot 1.13.2 #481
skript-mirror 1.0.0

**Comment by btk5h** [comment]
This has been fixed on the 2.x branch.

**Comment by TrademarkTM** [comment]
@btk5h Could you release a 1.0.x version with the log handlers fix?
It's impossible to use 2.3.1 and skript-mirror, and 2.x doesn't seem stable enough to be used yet.

Thanks.

**Comment by YellowZaki** [comment]
@btk5h I tried 1.0 with the fixes of https://github.com/btk5h/skript-mirror/commit/bbaefd71cd90674c1e34404d00b53cbc0408f57a.

The log handles messages don't appear but the addon doesn't work at all. 
The same when using 2.0.

**Comment by YellowZaki** [comment]
@btk5h how can this be a medium priority? Server won't start sometimes in 7 hours so autorestart is useless.

**Comment by btk5h** [comment]
> @btk5h how can this be a medium priority? Server won't start sometimes in 7 hours so autorestart is useless.

I have no confirmation that the server freezing is related to this bug.

**Comment by YellowZaki** [comment]
@btk5h yes, it is related to that bug. I've compiled the version with that patch and it is working perfect now. 
I don't know why but when I compiled with Gradle the addon didn't work at all but when I manually compiled it it worked.

**Comment by btk5h** [comment]
I don't really have the time to backport the fixes from 2.x and test them myself, and skript-mirror 1.x doesn't target newer versions of Skript, so this isn't a very high priority for me.

I will accept a PR from anyone who wants to backport the fixes and test skript-mirror themselves though.

**Comment by yambriz** [comment]
am haveing this issue may someone send me a download on a working version
