### ISSUE TITLE
Skript#exception NoSuchMethodError in Util

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#12]
**Issue:**
Something happens to cause a NoSuchMethod error with Skript#exception
___
**Versions:**
- Skript 2.2-SNAPSHOT (also occurs on Skript 2.2-dev25)
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.7.1
___
**Script:**
```
command noSuchMethod:
  trigger:
    import "org.bukkit.Bukkit"
    {Bukkit}.getPluginManager().getPlugin("Skript").getClass().getClassLoader();
```
___
**Output:**
```
[22:39:58 ERROR]: Could not pass event ServerCommandEvent to Skript v2.2-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.Skript.exception(Ljava/lang/Throwable;[Ljava/lang/String;)Ljava/util/EmptyStackException;
        at com.btk5h.skriptmirror.Util.lambda$propagateErrors$15(Util.java:89) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_111]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_111]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_111]
        at com.btk5h.skriptmirror.skript.ExprJavaCall.createCallSite(ExprJavaCall.java:124) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1126) ~[?:1.8.0_111]
        at com.btk5h.skriptmirror.skript.ExprJavaCall.getCallSite(ExprJavaCall.java:101) ~[?:?]
        at com.btk5h.skriptmirror.skript.ExprJavaCall.selectMethod(ExprJavaCall.java:274) ~[?:?]
        at com.btk5h.skriptmirror.skript.ExprJavaCall.invoke(ExprJavaCall.java:167) ~[?:?]
        at com.btk5h.skriptmirror.skript.ExprJavaCall.getAll(ExprJavaCall.java:411) ~[?:?]
        at com.btk5h.skriptmirror.skript.ExprJavaCall.check(ExprJavaCall.java:426) ~[?:?]
        at com.w00tmast3r.skquery.elements.conditions.CondBoolean.check(CondBoolean.java:19) ~[?:?]
        at ch.njol.skript.lang.Condition.run(Condition.java:58) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:269) ~[?:?]
        at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:180) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        ... 9 more
[22:39:58 WARN]: Unexpected exception while parsing console command "noSuchMethod"
java.lang.NullPointerException
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by xXAndrew28Xx** [comment]
Can reproduce.
