### ISSUE TITLE
reflection error

### ISSUE THREAD

**Issue by noy98** [btk5h/skript-mirror#125]
**Describe the bug**
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2110)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[19:07:04] [Server thread/WARN] []: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.util.Util.func_181617_a(Util.java:50)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:842)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633)
[19:07:04] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
[19:07:04] [Server thread/WARN] []: java.lang.IllegalAccessException: Class com.gmail.thelimeglass.Utils.ReflectionUtil can not access a member of class net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1 with modifiers "public"
[19:07:04] [Server thread/WARN] []: 	at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at com.gmail.thelimeglass.Utils.ReflectionUtil.sendPacket(ReflectionUtil.java:66)
[19:07:04] [Server thread/WARN] []: 	at com.gmail.thelimeglass.ReflectionSyntax.EffTitle.execute(EffTitle.java:124)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.Effect.run(Effect.java:52)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[19:07:04] [Server thread/WARN] []: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:07:04] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[19:07:04] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2110)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[19:07:04] [Server thread/WARN] []: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.util.Util.func_181617_a(Util.java:50)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:842)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633)
[19:07:04] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
[19:07:04] [Server thread/WARN] []: java.lang.IllegalAccessException: Class com.gmail.thelimeglass.Utils.ReflectionUtil can not access a member of class net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1 with modifiers "public"
[19:07:04] [Server thread/WARN] []: 	at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at com.gmail.thelimeglass.Utils.ReflectionUtil.sendPacket(ReflectionUtil.java:66)
[19:07:04] [Server thread/WARN] []: 	at com.gmail.thelimeglass.ReflectionSyntax.EffTitle.execute(EffTitle.java:128)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.Effect.run(Effect.java:52)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[19:07:04] [Server thread/WARN] []: 	at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[19:07:04] [Server thread/WARN] []: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:07:04] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[19:07:04] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2110)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[19:07:04] [Server thread/WARN] []: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.util.Util.func_181617_a(Util.java:50)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:842)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779)
[19:07:04] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633)
[19:07:04] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)**To reproduce**
Steps to reproduce the behavior. If applicable, add a script or code snippet here.

**Expected behavior**

**Screenshots**

**Server information**
- skript-mirror: 0.19.1
- Skript: 2.2. dev36
- Bukkit: catserver
- Minecraft: 1.12.2
- Java: 8
- OS:

**Additional context**

**Comment by btk5h** [comment]
Not a skript-mirror issue or not enough information to determine whether this is a skript-mirror issue.
