### ISSUE TITLE
NPE can occur when getting a field

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#13]
**Issue:**
An NPE can occur when getting a field
___
**Versions:**
- Skript 2.2-SNAPSHOT
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.7.1
___
**Script:**
```
#npe here
command npe:
  trigger:
    set {_thing} to {_not set}.."SOMETHING"!

#npe here again
command npe2:
  trigger:
    set {_thing} to {_not set}.SOMETHING!
```
___
**Output:**
```
>npe
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! [Skript] Severe Error:
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:48:56 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[22:48:56 ERROR]: #!#! and check whether this error has already been reported.
[22:48:56 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[22:48:56 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:48:56 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:48:56 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! Stack trace:
[22:48:56 ERROR]: #!#! java.lang.NullPointerException
[22:48:56 ERROR]: #!#!     at ch.njol.skript.lang.Variable.change(Variable.java:383)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:269)
[22:48:56 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:180)
[22:48:56 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[22:48:56 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:48:56 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[22:48:56 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[22:48:56 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:48:56 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:48:56 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[22:48:56 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[22:48:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
[22:48:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[22:48:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[22:48:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[22:48:56 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! Version Information:
[22:48:56 ERROR]: #!#!   Skript: 2.2-SNAPSHOT
[22:48:56 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[22:48:56 ERROR]: #!#!   Minecraft: 1.8.8
[22:48:56 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[22:48:56 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! Running CraftBukkit: false
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! Current node: null
[22:48:56 ERROR]: #!#! Current item: set {_thing}(as java.lang.Object) to java call
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! Thread: Server thread
[22:48:56 ERROR]: #!#!
[22:48:56 ERROR]: #!#! End of Error.
[22:48:56 ERROR]: #!#!
[22:48:56 INFO]: An internal error occurred while attempting to perform this command.
[22:48:56 INFO]: Unknown command. Type "/help" for help.
>npe2
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! [Skript] Severe Error:
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:49:07 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[22:49:07 ERROR]: #!#! and check whether this error has already been reported.
[22:49:07 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[22:49:07 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:49:07 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:49:07 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! Stack trace:
[22:49:07 ERROR]: #!#! java.lang.NullPointerException
[22:49:07 ERROR]: #!#!     at ch.njol.skript.lang.Variable.change(Variable.java:383)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:269)
[22:49:07 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:180)
[22:49:07 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[22:49:07 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:49:07 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[22:49:07 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[22:49:07 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:49:07 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:49:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[22:49:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[22:49:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
[22:49:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[22:49:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[22:49:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[22:49:07 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! Version Information:
[22:49:07 ERROR]: #!#!   Skript: 2.2-SNAPSHOT
[22:49:07 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[22:49:07 ERROR]: #!#!   Minecraft: 1.8.8
[22:49:07 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[22:49:07 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! Running CraftBukkit: false
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! Current node: null
[22:49:07 ERROR]: #!#! Current item: set {_thing}(as java.lang.Object) to (unspecified)#SOMETHING
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! Thread: Server thread
[22:49:07 ERROR]: #!#!
[22:49:07 ERROR]: #!#! End of Error.
[22:49:07 ERROR]: #!#!
[22:49:07 INFO]: An internal error occurred while attempting to perform this command.

```

**Comment by xXAndrew28Xx** [comment]
Can reproduce.
