### ISSUE TITLE
BukkitEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by DDuart** [btk5h/skript-mirror#136]
**Server information**
- skript-mirror: 2.0.0
- Skript: 2.4-beta5
- Bukkit: paper 1.14.4
- Minecraft: 1.14.4

**Additional context**
[18:30:57 ERROR]: Could not pass event AsyncPlayerChatEvent to skript-mirror v2.0.0-SNAPSHOT
java.lang.IllegalStateException: BukkitEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-167]
        at com.btk5h.skriptmirror.skript.reflect.EvtByReflection.lambda$static$0(EvtByReflection.java:44) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.4.jar:git-Paper-167]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Patbox** [comment]
Is there any chanse of this being fixed?
