### ISSUE TITLE
Java 13 breaks skript-mirror

### ISSUE THREAD

**Issue by Plutoren** [btk5h/skript-mirror#148]
**Describe the bug**
I attempted to update my server to Java 13 and found that skript-mirror was the only plugin that broke. The stable version didn't load and the dev version loaded but caused skript itself to abort when loading skripts. When force loading individual skripts it causes an internal error

**To reproduce**
Import something in a skript on Java 13 (among other problems I am sure)

**Expected behavior**
No internal errors would occur and the server would not explode

**Server information**
- skript-mirror: 2.0.0-SNAPSHOT (Also tried 0.19.1)
- Skript: 2.4
- Bukkit: Paper-235 1.14.4 (3 versions behind)
- Minecraft: 1.14.4
- Java: 13
- OS: Debian

**Additional context**
Startup log where Skript is like nah bro and loads 200 skripts in less than a second because it aborts
https://pastebin.com/PLsti4MQ

I could be incorrect in assuming skript-mirror is the only issue here and skript itself might be problematic on Java 13 as well but it was clear that things like import were causing errors while other skript features were working.

**Comment by btk5h** [comment]
This will be fixed in later version of skript-mirror when we can target a
more stable version of Skript.

**Comment by galacticwarrior9** [comment]
[Here ](https://pastebin.com/A8dM3vf8) is the startup error I receive on Java 13, given the Pastebin link in the OP is now invalid.

**Comment by Patbox** [comment]
Also doesn't work work with java 14.

skript-mirror: 2.0.0-SNAPSHOT
Skript: 2.4.1
Bukkit: Tunity-b2e87f8
Minecraft: 1.15.2
Java: 14
OS: Linux Mint
```
[08:29:15 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.btk5h.skriptmirror.util.SkriptReflection
	at com.btk5h.skriptmirror.skript.custom.CustomImport.updateImports(CustomImport.java:131) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.CustomImport.registerImport(CustomImport.java:123) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.CustomImport.access$100(CustomImport.java:25) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.CustomImport$SectionImport.lambda$init$0(CustomImport.java:75) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.btk5h.skriptmirror.skript.custom.CustomImport$SectionImport.init(CustomImport.java:75) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1264) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1235) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:684) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380) ~[?:?]
	at ch.njol.skript.Skript.reload(Skript.java:917) ~[?:?]
	at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:156) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	... 17 more

```
