### ISSUE TITLE
Severe Error when a script disable other script

### ISSUE THREAD

**Issue by masmc05** [btk5h/skript-mirror#151]
**Describe the bug**
I downloaded tab completer api (https://forums.skunity.com/resources/tab-completer-api.579/), it works well but on server start and reload , my script that need this script to work make spam in console , so i added in tab completer :
```
on load:
    wait for 2 seconds
    enable script "flowerbattle.sk"
on unload:
    disable script "flowerbattle.sk"
```
when it try do disable my script , a eror comes in console : 
[10:53:21 CEST INFO]: [Skript] Reloading all scripts...
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! [Skript] Severe Error:
[10:53:21 CEST ERROR]: #!#! Exception occurred in Skript's main command
[10:53:21 CEST ERROR]: #!#! Used command: /skript reload scripts
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! Something went horribly wrong with Skript.
[10:53:21 CEST ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:53:21 CEST ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[10:53:21 CEST ERROR]: #!#! Here is full list of them:
[10:53:21 CEST ERROR]: #!#! skript-mirror (https://github.com/btk5h/skript-mirror) 
[10:53:21 CEST ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[10:53:21 CEST ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[10:53:21 CEST ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[10:53:21 CEST ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[10:53:21 CEST ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[10:53:21 CEST ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! Stack trace:
[10:53:21 CEST ERROR]: #!#! java.util.ConcurrentModificationException
[10:53:21 CEST ERROR]: #!#!     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
[10:53:21 CEST ERROR]: #!#!     at java.util.ArrayList$Itr.next(ArrayList.java:859)
[10:53:21 CEST ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeAllTriggers(SkriptEventHandler.java:250)
[10:53:21 CEST ERROR]: #!#!     at ch.njol.skript.Skript.disableScripts(Skript.java:904)
[11:53] 
БОТ
 CALIDARO: [10:53:21 CEST ERROR]: #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.java:925)
[10:53:21 CEST ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:160)
[10:53:21 CEST ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[10:53:21 CEST ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[10:53:21 CEST ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[10:53:21 CEST ERROR]: #!#!     at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574)
[10:53:21 CEST ERROR]: #!#!     at com.gmail.seasonguy445.fsdiscordbot.BotCore.lambda$3(BotCore.java:149)
[10:53:21 CEST ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[10:53:21 CEST ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[10:53:21 CEST ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[10:53:21 CEST ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[10:53:21 CEST ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[10:53:21 CEST ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[10:53:21 CEST ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! Version Information:
[10:53:21 CEST ERROR]: #!#!   Skript: 2.4.1 (latest)
[10:53:21 CEST ERROR]: #!#!     Flavor: skriptlang-github
[10:53:21 CEST ERROR]: #!#!     Date: 2019-12-22
[10:53:21 CEST ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[10:53:21 CEST ERROR]: #!#!   Minecraft: 1.12.2
[10:53:21 CEST ERROR]: #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b04)
[10:53:21 CEST ERROR]: #!#!   OS: Linux amd64 5.4.0-0.bpo.3-amd64
[10:53:21 CEST ERROR]: #!#!
[11:53] 
БОТ
 CALIDARO: [10:53:21 CEST ERROR]: #!#! Server platform: Spigot
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! Current node: null
[10:53:21 CEST ERROR]: #!#! Current item: null
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! Thread: Server thread
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! Language: english
[10:53:21 CEST ERROR]: #!#! Link parse mode: DISABLED
[10:53:21 CEST ERROR]: #!#! 
[10:53:21 CEST ERROR]: #!#! End of Error.
[10:53:21 CEST ERROR]: #!#!
and after that it disable my script but doesn't enable , at second reload it enable perfectly, i disable skript-mirror and no eror comes when i do the same, and my script is disabled and after enabled
**To reproduce**
Steps to reproduce the behavior. If applicable, add a script or code snippet here.
/sk reload scripts
**Expected behavior**
skript to load all expresions from tab completer api and after that to load my script that uses them
**Screenshots**

**Server information**
- skript-mirror: skript-mirror-0.19.1.jar
- Skript: 
- Bukkit: 
- Minecraft: 
- Java: 
- OS:
(this is in eror)
Version Information:
[10:53:21 CEST ERROR]: #!#!   Skript: 2.4.1 (latest)
[10:53:21 CEST ERROR]: #!#!     Flavor: skriptlang-github
[10:53:21 CEST ERROR]: #!#!     Date: 2019-12-22
[10:53:21 CEST ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[10:53:21 CEST ERROR]: #!#!   Minecraft: 1.12.2
[10:53:21 CEST ERROR]: #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b04)
[10:53:21 CEST ERROR]: #!#!   OS: Linux amd64 5.4.0-0.bpo.3-amd64
**Additional context**

**Comment by btk5h** [comment]
I don't think this is a skript-mirror issue, this sounds like a limitation of Skript's script loader

**Comment by masmc05** [comment]
i founded a newer version : 1.0.0 , is the same eror

**Comment by masmc05** [comment]
> I don't think this is a skript-mirror issue, this sounds like a limitation of Skript's script loader

and i can't do anything ?
