### ISSUE TITLE
biome error

### ISSUE THREAD

**Issue by arts7493** [btk5h/skript-mirror#159]
**Describe the bug**

if other plugin change biome, console error

[01:42:41] [Craft Scheduler Thread - 5593/INFO]: [BentoBox] [Biomes] Veritas_in_Ryus change biome in loaded chunks to FLOWER_FOREST from x=21456:21695 z=33504:33743 while standing on x=21578 z=33634
[01:42:41] [Craft Scheduler Thread - 5593/ERROR]: Could not pass event BiomeChangedEvent to skript-mirror v2.0.0-SNAPSHOT
java.lang.IllegalStateException: BukkitEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Paper-378]
	at com.btk5h.skriptmirror.skript.reflect.EvtByReflection.lambda$static$0(EvtByReflection.java:44) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-378]
	at world.bentobox.biomes.tasks.BiomeUpdateTask.run(BiomeUpdateTask.java:132) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-378]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-378]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
**To reproduce**
Steps to reproduce the behavior. If applicable, add a script or code snippet here.

**Expected behavior**

**Screenshots**

**Server information**
- skript-mirror: [14:03:24] [Server thread/INFO]: skript-mirror version 2.0.0-SNAPSHOT
[14:03:24] [Server thread/INFO]: Reflection utilities for Skript
[14:03:24] [Server thread/INFO]: Website: https://github.com/btk5h/skript-mirror
[14:03:24] [Server thread/INFO]: Author: Bryan Terce <bryan.terce@gmail.com>
- Skript: 2.4.1
- Bukkit: paper 1.15.2
- Minecraft: 1.15.2
- Java: openjdk 1.8
- OS: window

**Additional context**

**Comment by Pikachu920** [comment]
`com.btk5h.skriptmirror.skript.reflect.EvtByReflection.lambda$static$`

The issue is with one of your skript-mirror events, I believe they already have an issue open for this too
