### ISSUE TITLE
Using an invalid type in syntax is allowed

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#19]
**Issue:**
Using an invalid type in syntax is allowed
___
**Versions:**
- Skript 2.2-dev25
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.8.3
___
**Script:**
```
effect grab %invalidtype%:
  continue returning expression 1

on script load:
  grab 1
```
___
**Output:**
```
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! [Skript] Severe Error:
[22:42:10 ERROR]: #!#! Unexpected error while executing effect command 'grab 1' by 'CONSOLE'
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:42:10 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[22:42:10 ERROR]: #!#! and check whether this error has already been reported.
[22:42:10 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[22:42:10 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:42:10 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:42:10 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! Stack trace:
[22:42:10 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for invalidtype
[22:42:10 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
[22:42:10 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1390)
[22:42:10 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)
[22:42:10 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[22:42:10 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[22:42:10 ERROR]: #!#!     at ch.njol.skript.lang.Effect.parse(Effect.java:76)
[22:42:10 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:286)
[22:42:10 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:175)
[22:42:10 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[22:42:10 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:42:10 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[22:42:10 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[22:42:10 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:42:10 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:42:10 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[22:42:10 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[22:42:10 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
[22:42:10 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[22:42:10 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[22:42:10 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[22:42:10 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! Version Information:
[22:42:10 ERROR]: #!#!   Skript: 2.2-dev25
[22:42:10 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[22:42:10 ERROR]: #!#!   Minecraft: 1.8.8
[22:42:10 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[22:42:10 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! Running CraftBukkit: false
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! Current node: null
[22:42:10 ERROR]: #!#! Current item: null
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! Thread: Server thread
[22:42:10 ERROR]: #!#!
[22:42:10 ERROR]: #!#! End of Error.
[22:42:10 ERROR]: #!#!
```

**Comment by btk5h** [comment]
Right now, there's no way to validate patterns before using them. There's also no way to catch SkriptAPIExceptions, so I can't suppress this error either.
