### ISSUE TITLE
NPE occurs when getting null expression

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#31]
**Issue:**
An NPE occurs when getting null expression
___
**Versions:**
- Skript 2.2-dev32d
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.8.3
___
**Script:**
```
effect example [%-string%]:
  broadcast expression 1
```
___
**Output:**
```
[01:42:16 INFO]: [Skript] sky_high issued effect command: example
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! [Skript] Severe Error:
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! Something went horribly wrong with Skript.
[01:42:16 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[01:42:16 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[01:42:16 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[01:42:16 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[01:42:16 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[01:42:16 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! Stack trace:
[01:42:16 ERROR]: #!#! java.lang.NullPointerException
[01:42:16 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.CustomSyntaxExpression.get(CustomSyntaxExpression.java:28)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpression.java:78)
[01:42:16 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.ExprExpression.getAll(ExprExpression.java:77)
[01:42:16 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.ExprExpression.getArray(ExprExpression.java:66)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:67)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[01:42:16 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.CustomEffect$EffectHandler.invokeEffect(CustomEffect.java:158)
[01:42:16 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.CustomEffect$EffectHandler.execute(CustomEffect.java:139)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:279)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:212)
[01:42:16 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[01:42:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftFuture.run(CraftFuture.java:89)
[01:42:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[01:42:16 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[01:42:16 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[01:42:16 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[01:42:16 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[01:42:16 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! Version Information:
[01:42:16 ERROR]: #!#!   Skript: 2.2-dev32d
[01:42:16 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[01:42:16 ERROR]: #!#!   Minecraft: 1.8.8
[01:42:16 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[01:42:16 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! Running CraftBukkit: false
[01:42:16 ERROR]: #!#! Running Spigot (or compatible): true
[01:42:16 ERROR]: #!#! Running Paper (or compatible): true
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! Current node: null
[01:42:16 ERROR]: #!#! Current item: broadcast expression 1
[01:42:16 ERROR]: #!#! Thread: Server thread
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! Language: english
[01:42:16 ERROR]: #!#! Link parse mode: DISABLED
[01:42:16 ERROR]: #!#!
[01:42:16 ERROR]: #!#! End of Error.
[01:42:16 ERROR]: #!#!

[01:42:48 INFO]: [Skript] sky_high issued effect command: example "asd"
[01:42:48 INFO]: asd
```

**Comment by Pikachu920** [comment]
this is fixed now
