### ISSUE TITLE
ArrayIndexOutOfBoundsException occurs with some varargs methods

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#51]
**Describe the bug**
An ArrayIndexOutOfBoundsException occurs when using a javacall with a javatype in it's args

**To reproduce**
```
import:
  ch.njol.skript.Skript
  org.bukkit.Server

on script load:
  Skript.methodExists(Server, "");
```

**Expected behavior**
The method is called

**Server information**
- skript-mirror: 0.12.1
```
[23:44:07 ERROR]: #!#!   Skript: 2.2-dev35b
[23:44:07 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[23:44:07 ERROR]: #!#!   Minecraft: 1.8.8
[23:44:07 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[23:44:07 ERROR]: #!#!   OS: Windows 10 amd64 10.0
```

**Additional context**
```
[23:44:07 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 1
[23:44:07 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.matchesArgs(ExprJavaCall.java:292)
[23:44:07 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.lambda$selectMethod$8(ExprJavaCall.java:274)
[23:44:07 ERROR]: #!#!     at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[23:44:07 ERROR]: #!#!     at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
[23:44:07 ERROR]: #!#!     at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[23:44:07 ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
[23:44:07 ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[23:44:07 ERROR]: #!#!     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[23:44:07 ERROR]: #!#!     at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[23:44:07 ERROR]: #!#!     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[23:44:07 ERROR]: #!#!     at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[23:44:07 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.selectMethod(ExprJavaCall.java:275)
[23:44:07 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.invoke(ExprJavaCall.java:165)
[23:44:07 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.getAll(ExprJavaCall.java:417)
[23:44:07 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.getArray(ExprJavaCall.java:392)
[23:44:07 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:440)
[23:44:07 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:604)
[23:44:07 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[23:44:07 ERROR]: #!#!     at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:67)
[23:44:07 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[23:44:07 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:281)
[23:44:07 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:180)
[23:44:07 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[23:44:07 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:44:07 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[23:44:07 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[23:44:07 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[23:44:07 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:44:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[23:44:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[23:44:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
[23:44:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[23:44:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[23:44:07 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[23:44:07 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
```

**Comment by btk5h** [comment]
It actually looks like this bug may be caused by varargs methods, not javatype parameters?

**Comment by Pikachu920** [comment]
could be, i only titled it this way because the issue did not occur without a javatype in the params. I didn't do much testing beyond that.
