### ISSUE TITLE
Materials do not work in effects

### ISSUE THREAD

**Issue by UzumakiYT** [btk5h/skript-mirror#64]
**Describe the bug**
Materials do not work in effects

**To reproduce**

`effect try %iteck stack%: #%material%, %item%
	trigger:		
		broadcast "%expression-1%"
	
command test:
	trigger:
		try stone`

**Error**

`[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! [Skript] Severe Error:
[00:31:41 ERROR]: #!#! Could not load pubg.sk
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! Something went horribly wrong with Skript.
[00:31:41 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:31:41 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:31:41 ERROR]: #!#! Here is full list of them:
[00:31:41 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skript-mirror TuSKe (github.com/Tuke-Nuke/TuSKe) SkStuff SkQuery
[00:31:41 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:31:41 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:31:41 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:31:41 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:31:41 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:31:41 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[00:31:41 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! Stack trace:
[00:31:41 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for iteck stack
[00:31:41 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:621)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:434)
[00:31:41 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[00:31:41 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:31:41 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:31:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[00:31:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634)
[00:31:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[00:31:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[00:31:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[00:31:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[00:31:41 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! Version Information:
[00:31:41 ERROR]: #!#!   Skript: 2.2-dev36
[00:31:41 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[00:31:41 ERROR]: #!#!   Minecraft: 1.12.2
[00:31:41 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[00:31:41 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! Server platform: Spigot
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! Current node: try stone (pubg.sk, line 38)
[00:31:41 ERROR]: #!#! Current item: null
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! Thread: Server thread
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! Language: english
[00:31:41 ERROR]: #!#! Link parse mode: DISABLED
[00:31:41 ERROR]: #!#!
[00:31:41 ERROR]: #!#! End of Error.
[00:31:41 ERROR]: #!#!`

**Server information**
- skript-mirror: last 
- Skript: dev27, dev 36
- Minecraft: spigot 1.8.8, 1.12
- Java: 8
- OS: windows

**Comment by btk5h** [comment]
The issue is that "iteck stack" is not a valid type.

**Comment by UzumakiYT** [comment]
%material%, %item%?
